# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBodyParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllFeelings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodypartToSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.AllBodyParts')),
            ],
        ),
        migrations.CreateModel(
            name='FeelingsToDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.AllDiseases')),
                ('feeling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.AllFeelings')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsToDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.AllDiseases')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.AllSymptoms')),
            ],
        ),
        migrations.AddField(
            model_name='bodyparttosymptom',
            name='symptom_to_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.SymptomsToDisease'),
        ),
    ]
