# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTechUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeelings',
            name='permuterm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
