# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTechUser', '0002_tempsymptomstodisease_tempxallfeelings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskingSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
