# Generated by Django 2.1.1 on 2018-09-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedTechUser', '0002_allfeelings_permuterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyparttosymptom',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='bodyparttosymptom',
            name='symptom_to_disease',
        ),
        migrations.AddField(
            model_name='allbodyparts',
            name='permuterm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alldiseases',
            name='permuterm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='allsymptoms',
            name='permuterm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='symptomstodisease',
            name='body_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedTechUser.AllBodyParts'),
        ),
        migrations.AlterField(
            model_name='allfeelings',
            name='permuterm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BodypartToSymptom',
        ),
    ]
