# Generated by Django 2.1.1 on 2018-09-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTechUser', '0003_auto_20180921_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feelingstodisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='feelingstodisease',
            name='feeling',
        ),
        migrations.AddField(
            model_name='allfeelings',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptomstodisease',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptomstodisease',
            name='symptom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AllDiseases',
        ),
        migrations.DeleteModel(
            name='AllSymptoms',
        ),
        migrations.DeleteModel(
            name='FeelingsToDisease',
        ),
    ]
