# Generated by Django 2.1.1 on 2018-09-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedTechUser', '0004_auto_20180922_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfeelings',
            name='permuterm',
        ),
        migrations.AlterField(
            model_name='symptomstodisease',
            name='body_part',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
